name: Conventional PR Title
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]    

permissions:
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:          
          types: |
            feat
            fix
            perf
            refactor
            docs
            test
            build
            style
            ci
            chore
            revert
          scopes: |
            truvideoSdk
            truvideoSdkCamera
            truvideoApi
            telemetry
            di
            internalUtilities
            utilities
            cloudStorage
            coreDataUtilities
            networking
            externalUtilities
            registry
            storageKit
            mediaUpload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
